### ISSUE TITLE
mod_command ban doesnt work when in config

### ISSUE THREAD

**Issue by alandball** [DDRace/teeworlds#158]
When using config to set privileges
To set moderator access to ban/bans, 
I do mod_command for different commands

But for ban and bans it says 
No such command: 'ban' 
No such command: 'bans'

When I do it in server using f2 it works.

**Comment by heinrich5991** [comment]
This should fix it:

```
diff --git a/src/engine/shared/console.cpp b/src/engine/shared/console.cpp
index 1ae02c5..c7c521d 100644
--- a/src/engine/shared/console.cpp
+++ b/src/engine/shared/console.cpp
@@ -652,7 +652,7 @@ CConsole::CConsole(int FlagMask)
        Register("echo", "r", CFGFLAG_SERVER|CFGFLAG_CLIENT, Con_Echo, this, "Echo the text");
        Register("exec", "r", CFGFLAG_SERVER|CFGFLAG_CLIENT, Con_Exec, this, "Execute the specified file");

-       Register("mod_command", "s?i", CFGFLAG_SERVER, ConModCommandAccess, this, "Specify command accessibility for moderators");
+       Register("mod_command", "s?i", CFGFLAG_SERVER|CFGFLAG_STORE, ConModCommandAccess, this, "Specify command accessibility for moderators");
        Register("mod_status", "", CFGFLAG_SERVER, ConModCommandStatus, this, "List all commands which are accessible for moderators");
        Register("user_status", "", CFGFLAG_SERVER, ConUserCommandStatus, this, "List all commands which are accessible for users");
        Register("cmdlist", "", CFGFLAG_SERVER|CFGFLAG_CHAT, ConUserCommandStatus, this, "List all commands which are accessible for users");
```

The issue probably exists in vanilla too.

**Comment by Learath2** [comment]
Vanilla issue teeworlds/teeworlds#942

**Comment by alandball** [comment]
heinrich, unless I changed the code in the sources incorrectly, what you posted doesn't fix the problem.

**Comment by alandball** [comment]
its fixed, when greyfox updates code from oy/teeworlds it will be fixed

**Comment by alandball** [comment]
Hi, the commit from teeworlds to fix this has yet to be implemented.
Here is a link to oy's commit that he fixed it https://github.com/teeworlds/teeworlds/commit/9fee99b2f6429b7049fc078ddcdeae5e4c74a60b

**Comment by Learath2** [comment]
As oys branch is now on a active state 0.6 -> 0.7 we arent pushing anything from there to ddr branch

**Comment by Learath2** [comment]
Ill try to merge that by hand

**Comment by Learath2** [comment]
Done
